# Generated by Django 5.2.11 on 2026-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='targets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gestureevent',
            name='camera',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='GestureEvent',
        ),
    ]
