# Generated by Django 5.2.11 on 2026-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_targetperson_remove_gestureevent_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetperson',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='is_found',
            field=models.BooleanField(default=False),
        ),
    ]
