# Generated by Django 5.2.11 on 2026-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_targetperson_expires_at_targetperson_is_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetperson',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='crime',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='father_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='job',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='last_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='place_of_birth',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='targetperson',
            name='tazkira_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
