# Generated by Django 5.2.11 on 2026-04-04 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0004_targetperson_address_targetperson_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profiles/default.png', upload_to='profiles/security/')),
                ('badge_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('operator', 'Surveillance Operator'), ('supervisor', 'Shift Supervisor'), ('admin', 'System Administrator')], default='operator', max_length=20)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
